### ISSUE TITLE
Прекращение работы краулера

### ISSUE THREAD

**Issue by m-marina** [poul1x/Crawlic#1]
Добрый день. Решила воспользоваться вашим краулером, т.к. он наиболее точно удовлетворяет требованиям текущей задачи (обнаружение вредоносных файлов не играет главную роль).

С момента запуска проходит около получаса, и он прекращает работу после 2-ой фразы, т.к. не находит urls по следующим. В чем может быть проблема?
[phrases.txt](https://github.com/poul1x/Crawlic/files/3431622/phrases.txt)

Заранее благодарю за ответ.

**Comment by poul1x** [comment]
Здравствуйте, это типичная проблема. Crawler создаёт много однотипных запросов, из - за чего впоследствии поисковая система требует ввести [капчу](https://ru.wikipedia.org/wiki/%D0%9A%D0%B0%D0%BF%D1%87%D0%B0). Решений этого я не нашёл, кроме как подождать или сменить поисковую систему.
